package hosts

// host_skill_runs store helpers — one row per skill.start dispatch.
// P1c.3 writes here from the dock-side bot dispatch: starting row on
// envelope send, status update on each skill.event, finalize on exit.
//
// The table schema (per applySchema) was designed for long-lived
// daemons (status: starting/running/stopped + pid/listen_addr). For
// the coder skill — which is one-shot per chat message — we
// repurpose: status flows starting → running → succeeded | failed |
// cancelled, ended_at is set on terminal events, error_message holds
// the orchestration failure reason when present. pid + listen_addr
// stay unused for coder runs.

import (
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"time"
)

// HostSkillRun mirrors a row in host_skill_runs for the runs the
// dock-side dispatcher creates. Returned by createHostSkillRun so the
// caller has the run_id to embed in the skill.start envelope.
type HostSkillRun struct {
	ID           int64      `json:"id"`
	SkillID      int64      `json:"skill_id"`
	StartedAt    time.Time  `json:"started_at"`
	EndedAt      *time.Time `json:"ended_at,omitempty"`
	Status       string     `json:"status"`
	ErrorMessage string     `json:"error_message,omitempty"`
}

// createHostSkillRun inserts a row with status='starting' and
// returns the autogenerated id so the dispatcher can use it as the
// run_id in the skill.start envelope.
func (p *Plugin) createHostSkillRun(skillID int64, now time.Time) (int64, error) {
	if skillID <= 0 {
		return 0, errors.New("skill_id required")
	}
	var id int64
	err := p.DB.QueryRow(`
		INSERT INTO host_skill_runs (skill_id, started_at, status)
		VALUES ($1, $2, 'starting')
		RETURNING id`,
		skillID, now,
	).Scan(&id)
	if err != nil {
		return 0, fmt.Errorf("insert host_skill_run: %w", err)
	}
	return id, nil
}

// createHostSkillRunWithMeta is the P2 variant — populates meta_json
// at insert time (operator_user_id + arbitrary metadata for the
// skill kind). Used by the Shell skill's open endpoint; future
// daemon-style skills (proxy/wireguard) reuse the same.
func (p *Plugin) createHostSkillRunWithMeta(skillID int64, meta map[string]any, now time.Time) (int64, error) {
	if skillID <= 0 {
		return 0, errors.New("skill_id required")
	}
	if meta == nil {
		meta = map[string]any{}
	}
	metaJSON, err := json.Marshal(meta)
	if err != nil {
		return 0, fmt.Errorf("marshal meta: %w", err)
	}
	var id int64
	err = p.DB.QueryRow(`
		INSERT INTO host_skill_runs (skill_id, started_at, status, meta_json)
		VALUES ($1, $2, 'starting', $3::jsonb)
		RETURNING id`,
		skillID, now, string(metaJSON),
	).Scan(&id)
	if err != nil {
		return 0, fmt.Errorf("insert host_skill_run: %w", err)
	}
	return id, nil
}

// updateHostSkillRunStatus moves a run from one status to another
// without touching ended_at. Called on intermediate `skill.event
// state` frames (e.g. status="running").
func (p *Plugin) updateHostSkillRunStatus(runID int64, status string) error {
	_, err := p.DB.Exec(`UPDATE host_skill_runs SET status = $2 WHERE id = $1`, runID, status)
	return err
}

// finalizeHostSkillRun marks a run terminal (succeeded / failed /
// cancelled), sets ended_at, and stores an optional error message.
// Idempotent — re-running with the same status is fine.
func (p *Plugin) finalizeHostSkillRun(runID int64, status, errorMessage string, endedAt time.Time) error {
	_, err := p.DB.Exec(`
		UPDATE host_skill_runs
		SET status = $2,
		    ended_at = $3,
		    error_message = COALESCE(NULLIF($4, ''), error_message)
		WHERE id = $1`,
		runID, status, endedAt, errorMessage,
	)
	return err
}

// getBotHostSkillID returns the host_skill_id bound to a bot user,
// or 0 if the bot has no binding (= legacy path stays active). Errors
// only on unexpected DB failures — a missing bot row returns (0, nil)
// since the caller's "unbound = legacy" interpretation is the right
// thing for unknown bots too.
func (p *Plugin) getBotHostSkillID(botUserID string) (int64, error) {
	var skillID sql.NullInt64
	err := p.DB.QueryRow(`SELECT host_skill_id FROM bot_users WHERE user_id = $1`, botUserID).Scan(&skillID)
	if errors.Is(err, sql.ErrNoRows) {
		return 0, nil
	}
	if err != nil {
		return 0, err
	}
	if !skillID.Valid {
		return 0, nil
	}
	return skillID.Int64, nil
}

// getHostSkillForDispatch returns the (kind, host_id, config_json)
// needed to build a skill.start envelope. Pulls only the columns the
// dispatcher uses to keep the hot path tight.
type HostSkillDispatchInfo struct {
	HostSkillID int64
	HostID      string
	Kind        string
	ConfigJSON  []byte
}

func (p *Plugin) getHostSkillForDispatch(hostSkillID int64) (*HostSkillDispatchInfo, error) {
	var info HostSkillDispatchInfo
	var configText string
	err := p.DB.QueryRow(`
		SELECT id, host_id, kind, config_json::text
		FROM host_skills
		WHERE id = $1`,
		hostSkillID,
	).Scan(&info.HostSkillID, &info.HostID, &info.Kind, &configText)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	info.ConfigJSON = []byte(configText)
	return &info, nil
}

// getAgentTokenForHost returns the agent_token_id linked to a host,
// or "" if none — that's the bridge into agentHub.lookupByTokenID
// for finding the live WS connection.
func (p *Plugin) getAgentTokenForHost(hostID string) (string, error) {
	var tokenID sql.NullString
	err := p.DB.QueryRow(`SELECT agent_token_id FROM hosts WHERE id = $1`, hostID).Scan(&tokenID)
	if errors.Is(err, sql.ErrNoRows) {
		return "", nil
	}
	if err != nil {
		return "", err
	}
	if !tokenID.Valid {
		return "", nil
	}
	return tokenID.String, nil
}
